import { DatabaseProps } from '../utils/types';

export const initialData: DatabaseProps[] = [
  { code: '1', name: 'Receitas', type: 'Receita', acceptReleases: 'Não' },
  {
    code: '1.1',
    name: 'Taxa condominial',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  {
    code: '1.2',
    name: 'Reserva de dependência',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  { code: '1.3', name: 'Multas', type: 'Receita', acceptReleases: 'Sim' },
  { code: '1.4', name: 'Juros', type: 'Receita', acceptReleases: 'Sim' },
  {
    code: '1.5',
    name: 'Multa condominial',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  { code: '1.6', name: 'Água', type: 'Receita', acceptReleases: 'Sim' },
  { code: '1.7', name: 'Gás', type: 'Receita', acceptReleases: 'Sim' },
  {
    code: '1.8',
    name: 'Luz e energia',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  {
    code: '1.9',
    name: 'Fundo de reserva',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  {
    code: '1.10',
    name: 'Fundo de obras',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  {
    code: '1.11',
    name: 'Correção monetária',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  {
    code: '1.12',
    name: 'Transferência entre contas',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  {
    code: '1.13',
    name: 'Pagamento duplicado',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  { code: '1.14', name: 'Cobrança', type: 'Receita', acceptReleases: 'Sim' },
  { code: '1.15', name: 'Crédito', type: 'Receita', acceptReleases: 'Sim' },
  {
    code: '1.16',
    name: 'Água mineral',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  {
    code: '1.17',
    name: 'Estorno taxa de resgate',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  { code: '1.18', name: 'Acordo', type: 'Receita', acceptReleases: 'Sim' },
  { code: '1.19', name: 'Honorários', type: 'Receita', acceptReleases: 'Sim' },
  { code: '2', name: 'Despesas', type: 'Despesa', acceptReleases: 'Não' },
  { code: '2.1', name: 'Com pessoal', type: 'Despesa', acceptReleases: 'Não' },
  { code: '2.1.1', name: 'Salário', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '2.1.2',
    name: 'Adiantamento salarial',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.1.3', name: 'Hora extra', type: 'Despesa', acceptReleases: 'Sim' },
  { code: '2.1.4', name: 'Férias', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '2.1.5',
    name: '13º salário',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '2.1.6',
    name: 'Adiantamento 13º salário',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '2.1.7',
    name: 'Adicional de função',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '2.1.8',
    name: 'Aviso prévio',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.1.9', name: 'INSS', type: 'Despesa', acceptReleases: 'Sim' },
  { code: '2.1.10', name: 'FGTS', type: 'Despesa', acceptReleases: 'Sim' },
  { code: '2.1.11', name: 'PIS', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '2.1.12',
    name: 'Vale refeição',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '2.1.13',
    name: 'Vale transporte',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '2.1.14',
    name: 'Cesta básica',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '2.1.15',
    name: 'Acordo trabalhista',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.2', name: 'Mensais', type: 'Despesa', acceptReleases: 'Não' },
  {
    code: '2.2.1',
    name: 'Energia elétrica',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '2.2.2',
    name: 'Água e esgoto',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '2.2.3',
    name: 'Taxa de administração',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.2.4', name: 'Gás', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '2.2.5',
    name: 'Seguro obrigatório',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.2.6', name: 'Telefone', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '2.2.7',
    name: 'Softwares e aplicativos',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.3', name: 'Manutenção', type: 'Despesa', acceptReleases: 'Não' },
  { code: '2.3.1', name: 'Elevador', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '2.3.2',
    name: 'Limpeza e conservação',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.3.3', name: 'Jardinagem', type: 'Despesa', acceptReleases: 'Sim' },
  { code: '2.4', name: 'Diversas', type: 'Despesa', acceptReleases: 'Não' },
  {
    code: '2.4.1',
    name: 'Honorários de advogado',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.4.2', name: 'Xerox', type: 'Despesa', acceptReleases: 'Sim' },
  { code: '2.4.3', name: 'Correios', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '2.4.4',
    name: 'Despesas judiciais',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '2.4.5', name: 'Multas', type: 'Despesa', acceptReleases: 'Sim' },
  { code: '2.4.6', name: 'Juros', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '2.4.7',
    name: 'Transferência entre contas',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '3',
    name: 'Despesas bancárias',
    type: 'Despesa',
    acceptReleases: 'Não',
  },
  {
    code: '3.1',
    name: 'Registro de boletos',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '3.2',
    name: 'Processamento de boletos',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  {
    code: '3.3',
    name: 'Registro e processamento de boletos',
    type: 'Despesa',
    acceptReleases: 'Sim',
  },
  { code: '3.4', name: 'Resgates', type: 'Despesa', acceptReleases: 'Sim' },
  {
    code: '4',
    name: 'Outras receitas',
    type: 'Receita',
    acceptReleases: 'Não',
  },
  {
    code: '4.1',
    name: 'Rendimento de poupança',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
  {
    code: '4.2',
    name: 'Rendimento de investimentos',
    type: 'Receita',
    acceptReleases: 'Sim',
  },
];
